---
name : NMS module for Abills
url: https://diger.github.io/
output : docs

head_menu :
    ABillS : http://abills.net.ua/
    Screenshots : /screenshots.html
    Help : /help.html
    Github : https://github.com/diger/Nms


